### PR TITLE
Support opam

### PR DESCRIPTION
**Pull request by tmattio**
Work in progress, but here are the changes so far:

- Remove Pesy and add a custom dune file in test to keep the same structure as the templates (https://github.com/tmattio/spin/issues/42)

Remaining work:

- [X] Remove Console and Pastel as reason-native projects are not on Opam
- [x] Add dune release calls in release script

### CODE REVIEW

**Comment by citizen428** [comment]
I was following along the discussion on the [Reason forum](https://reasonml.chat/t/intersection-with-ocaml-ecosystem/2036/10), and I think a few good points were made there. Reason tools are new, and therefore not widely adopted in the bigger OCaml community, but that doesn't mean it will stay that way. 

I think it doesn't really matter much which way Spin goes for its own codebase, but I think if someone chooses Reason as language, the templates should probably default to Rely and esy-workflows, vs. Alcotest and dune when picking OCaml. They'll still be consistent overall (project organization etc), but they'll probably feel better to users of the respective languages. 

The way I imagine this:

1. During `spin new`, choose syntax.
2. If syntax is Reason, use Rely and esy. Otherwise Alcotest and dune.
3. Make both test framework and build system configurable as next steps in the process, like e.g. `vue-cli` does it.

More effort for sure, but IMHO the best experience for users.

**Comment by tmattio** [comment]
I agree, it does not feel right to remove Rely and Pastel for the templates.

Once again, a goal of Spin is to reduce the gap between the two communities. The fact that reason-native projects are not released on Opam has the consequence that they can only be used by Esy users (they could be used with Opam pins, but then from what I understand the package could not be published on Opam). So we end up having to choose between two things:

- Not using these libraries to unlock the release on Opam.
- Using these libraries and accepting that generated projects will only be available to Esy users.

Even though it saddens me to not use these libraries (especially Rely, which I prefer over Alcotest), the second solution widens the gap between the two communities, which is not aligned with Spin's goals.

I think Reason Native maintainers wanted to release the packages on Opam soon, once that's done, I think it would make sense to add back the libraries. (cc @jordwalke, is this still in the plans?).

As to using Esy for Reason and Opam for OCaml (I assume you meant Opam and not dune, as dune is used in Reason even if you use Esy), I don't think this is a direction we want to take: a takeaway of the discussion you linked to is that OCaml folks might be interested in using Esy as a package manager.

As an alternative, I would prefer to add a choice during the setup to choose the test framework, this way people could use Reason with Alcotest or OCaml with Rely if they want. Jordan made a good point that syntax will influence the type of API you will use, so using Rely in OCaml seems a bit awkard, but I don't think this should be a consideration of Spin given its goals. Users will just be able choose what they prefer.

**Comment by citizen428** [comment]
> Once again, a goal of Spin is to reduce the gap between the two communities.

👍 

> I assume you meant Opam and not dune, as dune is used in Reason even if you use Esy

I did indeed, not sure what happened there.

> I would prefer to add a choice during the setup to choose the test framework, this way people could use Reason with Alcotest or OCaml with Rely if they want. 

Yes, that's what I wanted too, I just wanted to make the default dependent on the previous choice of Reason vs OCaml.

**Comment by tmattio** [comment]
> Yes, that's what I wanted too, I just wanted to make the default dependent on the previous choice of Reason vs OCaml.

Oh, misundertood then. Completely aligned with that! Might not be very hard technically (just have to pass the default value through the template engine I think)

Also, if a release of reason-native packages on Opam is imminent, we could prepare for this and offer the choice of Rely and Alcotest in the templates already. The Opam release of Rely users would be broken for a while, but it would fix itself once Rely is released. All depends on the timeline, wouldn't make sense to have a temporary solution for 6 months IMO.

**Comment by tmattio** [comment]
I've been playing a bit more with the test setup.
There is an `optional` stanza in dune for the `library` stanza, so with a dune file like this:
```
(library
 (name My_lib_test)
 (public_name my-lib.test)
 (flags -open Base -linkall -g -w -9)
 ; Make the library optional to skip building test on Opam
 (optional)
 (libraries base rely.lib my-lib.lib)
 (modules
  (:standard \ test_runner)))

(test
 (name test_runner)
 (modules test_runner)
 (libraries base my-lib.test)
 (flags -open Base)
 (action
  (run %{test} -q --color=always)))
```

We could depend on Rely, while still being able to release on Opam. I've changed the templates to support both Alcotest and Rely, will make a PR soon!

**Comment by citizen428** [comment]
Oh, that's good news 😃 

I also found this in regards to Pastel:

https://github.com/facebookexperimental/reason-native/commit/d4ac1585b91e1e4206e3a6f9891c84543de14dfb#diff-0c6a0367da13abf7bec7dcbbaca64a65

> This allows projects to pin the opam files right from our git repo even if we don't publish the packages. But also, now we can publish the opam packages.

**Comment by tmattio** [comment]
Thanks for the link! From what I understand, you can pin an opam dependency to a git repository, but this is only for local development, this wouldn't allow a release on opam. Or is there a way to depend on a git repo from the opam file?

I've tried reverting to Rely and use the setup I mentionned above, unfortunately, Rely's output does not look good when doing that.

I've opened an issue here, for reference: https://github.com/facebookexperimental/reason-native/issues/240

**Comment by citizen428** [comment]
I honestly don't know enough about Opam to know whether or not one can publish a package with a pinned dependency. There is a `pin-depends` option though:

https://opam.ocaml.org/doc/Manual.html#opamfield-pin-depends

**Pull request merged**
